server:
  port: 9999
  servlet:
    context-path: /ylbx

spring:
  #数据源配置
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/ylbx?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456zr
      driver-class-name: com.mysql.cj.jdbc.Driver
  #  spring boot：2.7.11与swagger：2.9.2不兼容：Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      static-path-pattern: /**
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
##mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印 mybatis-plus 的执行日志
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.neuedu.ylbx.pojo,com.neuedu.ylbx.vo,com.neuedu.ylbx.dto

